name: Deploy
on: [push]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: mon.crcibernetica.com
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: /usr/local/bin/update-timerapp.sh